apiVersion: v1
kind: Namespace
metadata:
  name: webhook-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: init-injector-sa
  namespace: webhook-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: webhook-system
  name: configmap-reader
rules:
- apiGroups: [ "" ]
  resources: [ "configmaps" ]
  verbs: [ "get" ]
- apiGroups: [ "apps" ]
  resources: [ "deployments" ]
  verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: webhook-system
  name: webhook-configmap-reader
subjects:
- kind: ServiceAccount
  name: init-injector-sa
  namespace: webhook-system
roleRef:
  kind: Role
  name: configmap-reader
  apiGroup: rbac.authorization.k8s.io
